[book]
authors = ["Gabriel Hansson <gabrielhansson00@gmail.com>"]
language = "en"
multilingual = false
src = "book"
title = "`rops` Documentation"

[rust]
edition = "2021"

[build]
build-dir = "target/book"

[output.html]
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/gibbz00/rops"
edit-url-template = "https://github.com/gibbz00/rops/edit/main/{path}"
