[workspace]
resolver = "2"
members = [ "crates/*" ]

[workspace.dependencies]
age = "0.9"
anyhow = "1"
aes-gcm = { version = "0.10", features = ["std"] }
base64 = "0.21"
chrono = { version = "0.4", features = ["serde"] }
derive_more = "0.99"
generic-array = "0.14"
hex = "0.4"
impl-tools = "0.10"
indexmap = "2"
indoc = "2"
pretty_assertions = "1"
rand = "0.8"
regex = "1"
serde = { version = "1", features = ["derive"] }
serde_regex = "1"
serde_with = "3"
serde_yaml = "0.9"
sha2 = "0.10"
strum = { version = "0.25", features = ["derive"] }
textwrap = "0.16"
thiserror = "1"

[patch.crates-io]
# TEMP: https://github.com/str4d/rage/pull/420
age = { git = "https://github.com/gibbz00/rage", branch = "public_key_partial_eq" }
