[workspace]
resolver = "2"
members = [ "crates/*" ]

[workspace.dependencies]
age = "0.9"
aes-gcm = "0.10"
base64 = "0.21"
derive_more = "0.99"
indoc = "2"
rand = "0.8"
serde = { version = "1", features = ["derive"] }
serde_with = "3"
serde_yaml = "0.9"
strum = { version = "0.25.0", features = ["derive"] }
textwrap = "0.16"
thiserror = "1"

[patch.crates-io]
# TEMP: https://github.com/str4d/rage/pull/420
age = { git = "https://github.com/gibbz00/rage", branch = "public_key_partial_eq" }
