[package]
name = "rops-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
rops = { path = "../lib" }

anyhow.workspace = true
clap.workspace = true
console.workspace = true
ctrlc.workspace = true
regex.workspace = true
tempfile.workspace = true
thiserror.workspace = true
which.workspace = true

[dev-dependencies]
rops = { path = "../lib", features = ["test-utils"] }

pretty_assertions.workspace = true
