[package]
name = "rops-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
rops = { path = "../rops" }

anyhow.workspace = true
clap.workspace = true
thiserror.workspace = true

[dev-dependencies]
rops = { path = "../rops", features = ["test-utils"] }

pretty_assertions.workspace = true
